version: "3.9"
   
services:
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - ~/postgres/:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  backend:
    container_name: backend
    platform: linux/x86-64
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    # command: python3 taskmanager/manage.py runserver 0:8000
    command: >
      sh -c "python3 taskmanager/manage.py migrate && python3 taskmanager/manage.py runserver 0:8000"

    volumes:
      - ../backend:/backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - ALLOWED_HOSTS='*'
      - CACHE_TTL=60
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    platform: linux/x86-64
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    volumes:
      - ../frontend/public:/frontend/public
      - ../frontend/src:/frontend/src
    ports:
      - "5173:5173"
